import './globals.css'
import type { Metadata } from 'next'
import { Oswald } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client';

const oswald = Oswald({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Waitlist',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={oswald.className}>{children}</body>
      </UserProvider>
    </html>
  )
}
